"""Build the narrative notebook from the tested implementation; execution is separate.

Run: python scripts/build_notebook.py
Then: jupyter nbconvert --execute --to notebook --inplace Causal_AI_Experiment.ipynb
"""

import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
cells = []


def markdown(text):
    cells.append({"cell_type": "markdown", "metadata": {}, "source": text.strip() + "\n"})


def code(text, **metadata):
    cells.append(
        {
            "cell_type": "code",
            "metadata": metadata,
            "source": text.strip() + "\n",
            "execution_count": None,
            "outputs": [],
        }
    )


def implementation(module, names):
    """Inline complete definitions, including decorators, without local-module imports."""
    path = ROOT / "src" / "causal_hedging" / f"{module}.py"
    source = path.read_text()
    lines = source.splitlines()
    selected = []
    for node in ast.parse(source).body:
        name = getattr(node, "name", None)
        if isinstance(node, ast.Assign):
            name = getattr(node.targets[0], "id", None)
        if name in names:
            start = min([node.lineno] + [d.lineno for d in getattr(node, "decorator_list", [])])
            selected.append("\n".join(lines[start - 1 : node.end_lineno]))
    code(
        "\n\n\n".join(selected),
        implementation_source=f"src/causal_hedging/{module}.py",
        implementation_names=names,
    )


markdown(r"""
# Causal AI: when the pattern you learn is the policy you used
### A single-notebook experiment in commodity procurement hedging

**Question:** can a Transformer-PPO policy learn a seasonal price pattern generated by the company's own liquidation schedule—and does training on explicit interventions change its behavior when that schedule changes?

This notebook puts the full model code, economic assumptions, experiment, data tables and rendered charts in one reading sequence. The repository's Python package remains the tested implementation; the definitions below are inlined from it, so **you do not need to open other code files to follow or run the experiment**.

**Two distinct sources of evidence:**

- **Synthetic causal experiment:** a known structural model, with company liquidation effects specified by us. It is not causal discovery from market prices.
- **Real market context:** free daily WTI observations from EIA via FRED. Those prices alone do not identify a company's liquidation effect.

The saved outputs come from executing every code cell, including all six policy-training runs. GitHub can display the notebook without running Python.

## Reading and running

Read top to bottom, or jump to [results](#7-Measured-results-and-baselines) and [real market data](#9-Real-market-context:-WTI).

For a fresh environment, run this once in a notebook cell:

```python
%pip install "numpy>=1.26,<3" "pandas>=2.2,<4" "torch>=2.2,<3" "matplotlib>=3.8,<4" ipykernel
```

Then **Restart Kernel → Run All**. The full run uses CPU and may take a few minutes. From a cloned repository, `pip install -e '.[notebook]'` provides JupyterLab too. Exact reference model-library versions are in `requirements-reference.txt`.

The notebook is self-contained in code. It writes generated results into `notebook-runs/`, leaving committed reference results unchanged. The WTI section reads the separate `data/` snapshot when available; a standalone copy downloads public WTI data when it reaches that section. Set `REFRESH_WTI=True` to request a new snapshot explicitly.
""")
code("""import hashlib
import io
import json
import math
import platform
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from urllib.request import Request, urlopen

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from IPython.display import Markdown, display
from torch import nn
from torch.distributions import Categorical

%matplotlib inline

SEEDS = [11, 22, 33]
STEPS = 4096
TEST_PATHS = 8
REFRESH_WTI = False
ROOT = Path.cwd()
RUN_DIR = ROOT / "notebook-runs" / "full-experiment"
DATA_DIR = ROOT / "data"

torch.set_num_threads(1)
torch.use_deterministic_algorithms(True)
pd.set_option("display.precision", 3)
plt.rcParams.update({
    "figure.figsize": (13, 4.8), "figure.dpi": 120,
    "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.alpha": 0.2,
    "font.size": 11, "axes.titleweight": "bold",
})
COLORS = {"Observational PPO": "#dc674d", "Interventional PPO": "#138e82",
          "Always hedge": "#71809b", "Never hedge": "#a876c6", "50% hedge": "#c59b35"}
display(pd.Series({"Python": platform.python_version(), "PyTorch": torch.__version__,
                   "NumPy": np.__version__, "Seeds": str(SEEDS),
                   "Training steps / policy": STEPS, "Test paths / seed": TEST_PATHS},
                  name="Execution configuration").to_frame())""")
markdown(r"""
## 1 · Define the economic question

The business exposure is a **future commodity purchase**. Remaining unhedged can help if prices fall; this is not the mark-to-market P&L of already-owned inventory.

For a hedge fraction $h$ and four-week horizon $H$:

$$c_t=(1-h)(P_{t+H}-P_t)+0.15h,$$
$$u_t=-c_t-0.04\max(c_t,0)^2.$$

Positive cost means paying more than locking all volume at today's spot price before fees. The agent maximizes a risk-penalized utility, not raw profit. Weekly decisions cover separate procurement tranches; they do not form one self-financing trading portfolio. Costs are **synthetic index units**, not investment returns.

This simplified hedge locks today's spot-price proxy. Futures basis, margin, financing, position limits and market impact from the hedge itself are outside the model.

## 2 · Specify the structural causal model

$$P_t=100+1.5\sin(2\pi(w_t-1)/52)+U_t-8L_t+S_t,\quad U_t\sim N(0,0.7^2).$$

- $L_t$: the company's liquidation decision. It occurs in Q4 before entry, then in Q3 when the company responds to competitor entry at the start of **calendar year 9**.
- $S_t$: an unseen January year-10 supply shock, initially 12 index points, decaying over time.
- The sine is a deterministic exogenous seasonal component; $U_t$ is stochastic noise.

The competitor changes the company's schedule in this story; it has no separate price-effect term. This is a precise, specified scenario, not a factual reconstruction of a commodity market.
""")
implementation("scm", ["Config", "DEFAULT_CONFIG", "World", "make_world"])
code("""config = Config()
world = make_world(10000, config)
t = np.arange(len(world.price))
fig, axes = plt.subplots(1, 2, figsize=(14, 4.8))
axes[0].plot(t / 52 + 1, world.price, color="#263f65", linewidth=1.2)
axes[0].axvspan(9, 11, color="#138e82", alpha=0.08, label="Held-out years 9–10")
axes[0].axvline(9, color="#138e82", linestyle="--", label="Competitor entry")
axes[0].axvline(10, color="#dc674d", linestyle="--", label="January supply shock")
axes[0].set(title="Ten synthetic years: the schedule changes", xlabel="Calendar year", ylabel="Price index")
axes[0].legend(fontsize=9)
axes[1].plot(t / 52 + 1, world.seasonal, label="Exogenous seasonality", color="#71809b")
axes[1].plot(t / 52 + 1, -config.liquidation_effect * world.liquidation,
             label="Company liquidation", color="#dc674d")
axes[1].plot(t / 52 + 1, world.shock, label="Supply shock", color="#138e82")
axes[1].set(title="Known components, not estimated effects", xlabel="Calendar year", ylabel="Contribution to price")
axes[1].legend(fontsize=9)
fig.tight_layout()
plt.show()""")
markdown(r"""
## 3 · Intervene on liquidation, keeping the shocks fixed

A counterfactual question changes a mechanism: **what would the price path be if the company did not liquidate in Q4?** We compare `none` and `q4` schedules with the same noise realization and supply shock.

In this known additive model, $P_t^{do(Q4)}-P_t^{do(none)}=-8$ during Q4 and zero otherwise. This follows from the assumed structural equation. It is not an estimate extracted from WTI data.

Adding random noise to the observed history would not perform this intervention. Replacing the liquidation equation does.
""")
code("""no_liquidation = make_world(10000, config, "none")
q4_liquidation = make_world(10000, config, "q4")
np.testing.assert_array_equal(no_liquidation.noise, q4_liquidation.noise)
np.testing.assert_array_equal(no_liquidation.shock, q4_liquidation.shock)
contrast = q4_liquidation.price - no_liquidation.price
np.testing.assert_allclose(contrast, -8 * (t % 52 + 1 >= 40))

weeks = np.arange(1, 53)
year8 = slice(7 * 52, 8 * 52)
fig, axes = plt.subplots(1, 2, figsize=(14, 4.6))
axes[0].plot(weeks, no_liquidation.price[year8], label="do(no liquidation)", color="#138e82")
axes[0].plot(weeks, q4_liquidation.price[year8], label="do(Q4 liquidation)", color="#dc674d")
axes[0].set(title="Paired worlds · identical exogenous shocks", xlabel="Week of year", ylabel="Price index")
axes[0].legend()
axes[1].plot(weeks, contrast[year8], color="#dc674d", linewidth=2)
axes[1].set(title="Known intervention contrast", xlabel="Week of year", ylabel="Price difference")
for ax in axes:
    ax.axvspan(40, 52, color="#dc674d", alpha=0.08)
fig.tight_layout()
plt.show()
print("Verified: only the liquidation mechanism changes between the paired worlds.")""")
markdown(r"""
## 4 · Build the information set and training environments

Each decision sees **104 weekly prices** and cyclical week features. It does not see future prices, the liquidation variable, or the true seasonal decomposition. Price normalization uses fixed simulator constants, not held-out statistics.

Both policies train on the first eight years with an initial 104-observation warmup. Every four-week reward target remains strictly before year 9.

The observational environment replays the historical Q4 rule. The interventional environment samples `observed`, `none`, `q3` or `q4` at each episode reset, preserving the same historical exogenous noise. Thus the interventional policy receives extra structural knowledge via its training distribution. This is an **oracle-SCM intervention-training comparison**, not evidence that it learned causal structure without supervision.
""")
implementation("scm", ["features", "procurement_outcome", "TrainingEnv"])
code("""state = features(world, 200, config.history)
assert state.shape == (104, 3)
altered = make_world(10000, config)
altered.price[201:] += 1000
np.testing.assert_array_equal(state, features(altered, 200, config.history))

env = TrainingEnv(causal=True, seed=11)
env.reset()
done, decisions = False, 0
while not done:
    assert env.t + config.horizon < config.entry_year * 52
    _, _, done = env.step(0.5)
    decisions += 1
print(f"Verified: {decisions} training decisions per episode; no target crosses the holdout boundary.")
print("Verified: changing future prices leaves the current information set unchanged.")""")
markdown(r"""
## 5 · Transformer actor–critic and PPO

The last Transformer token attends to all 104 available observations. Two heads share its representation: the actor produces categorical probabilities over hedge fractions `[0, .25, .5, .75, 1]`; the critic estimates discounted utility.

This is an **actor–critic encoder**, not a separately trained price forecaster. Dropout is disabled so unchanged parameters give stable likelihoods. Discrete bounded actions avoid clipping a Gaussian action while still scoring it under the original density.
""")
implementation("ppo", ["HEDGES", "Policy"])
markdown(r"""
PPO compares the probability of **the same sampled action in the same state** before and after an update. Log-probabilities and advantages must be matching one-dimensional vectors. GAE stops at terminal boundaries; the environment continues across rollout batches and resets only when its training episode ends.

The implementation below uses the clipped surrogate objective, a critic loss, entropy regularization and gradient clipping. Utilities are divided by 10 for training stability; reported economic costs and utilities are unscaled.
""")
implementation("ppo", ["gae", "clipped_loss", "train", "probabilities"])
code("""try:
    clipped_loss(torch.zeros(64), torch.zeros(64, 1), torch.ones(64))
except ValueError:
    print("Verified: the original [64] versus [64, 1] broadcasting bug is rejected.")
else:
    raise AssertionError("PPO shape guard failed")
a, ret = gae([1, 2], [0, 0], [True, True], bootstrap=999)
np.testing.assert_allclose(ret, [1, 2])
print("Verified: terminal GAE targets do not incorporate the next episode.")""")
markdown(r"""
## 6 · Train and evaluate on paired held-out worlds

We train both policies for each of three seeds. Evaluation uses eight unseen noise realizations with identical price paths for all policies, including always-hedged, never-hedged and 50%-hedged baselines. Calendar years 9–10 are held out. The schedule change and shock magnitude are designed stress assumptions, not a random sample of future regimes.

Training samples categorical actions. Evaluation uses the probability-weighted **mean hedge** as a deterministic fractional hedge. The separate `p_under_half` field records the exact probability of a sampled categorical action below 50%. These are different quantities.

Test paths are shared across training seeds. We average paths within each seed before comparing policies, rather than treating all rows as independent experimental replications.
""")
implementation("experiment", ["run"])
code("""metrics = run(RUN_DIR, seeds=SEEDS, steps=STEPS, test_paths=TEST_PATHS)
evaluation = pd.read_csv(RUN_DIR / "evaluation.csv")
per_run = pd.read_csv(RUN_DIR / "per_run.csv")
summary = pd.read_csv(RUN_DIR / "summary.csv", index_col="policy")

assert not metrics["market_data_used_for_training"]
price_spread = evaluation.groupby(["seed", "path", "t"]).price.agg(lambda x: x.max() - x.min())
assert price_spread.max() == 0
assert evaluation.t.min() == config.entry_year * 52
print(f"Verified: all policies see the same prices in {TEST_PATHS} held-out paths per seed.")
print(f"Completed {len(SEEDS) * 2} training runs, {STEPS:,} transitions each.")""")
markdown(r"""
## 7 · Measured results and baselines
<a id="7-Measured-results-and-baselines"></a>

**How to read the table:** lower procurement cost is better; higher risk-penalized utility is better; lower worst-tranche cost means less severe downside in this stress test. These criteria need not select the same policy.

The standard deviation describes variation across training-seed means. Three seeds do not establish a reliable confidence interval or broad robustness. Baselines have zero training-seed variation because the same test paths are reused; their market-path risk is not zero.
""")
code("""order = list(COLORS)
display(summary.loc[order].round(3))
seed_means = per_run.groupby(["seed", "policy"])[["total_cost", "total_utility"]].mean()
fig, axes = plt.subplots(1, 2, figsize=(14, 4.8))
for ax, column, title in zip(axes, ["total_cost", "total_utility"],
                           ["Procurement cost ↓", "Risk-penalized utility ↑"]):
    means = [seed_means.xs(label, level="policy")[column].mean() for label in order]
    ax.barh(order, means, color=[COLORS[label] for label in order], alpha=0.85)
    for i, label in enumerate(order):
        values = seed_means.xs(label, level="policy")[column].values
        ax.scatter(values, np.full(len(values), i), color="#162c46", s=22, zorder=3)
    ax.invert_yaxis()
    ax.axvline(0, color="#71809b", linewidth=0.7)
    ax.set(title=title, xlabel="Synthetic index units; dots = training-seed means")
fig.tight_layout()
plt.show()

paired = pd.Series(metrics["paired_cost_reduction_by_seed"], name="Observational cost − interventional cost")
display(paired.rename_axis("Training seed").to_frame().round(3))
delta = metrics["paired_cost_reduction_mean"]
winner = "interventional" if delta > 0 else "observational" if delta < 0 else "neither"
display(Markdown(f"**Measured paired cost reduction: {delta:+.3f} index units.** "
                 f"The mean raw-cost comparison favors **{winner}** training in this run. "
                 "Compare the utility and fixed-hedge baselines before drawing a conclusion."))""")
markdown(r"""
## 8 · Inspect behavior, rather than assuming the story

A lower average cost does not establish that the agent discovered a crisp Q4 rule. Plot the deployed mean hedge and inspect the exact week-40 under-hedging probabilities. In the reference run, learned-policy differences are modest. There is **no assumed or targeted 94% result**.

The chart pools weeks across two held-out years and the test paths. The table separates the two calendar years; neither is a pre-entry training statistic.
""")
code("""learned = evaluation[evaluation.policy.isin(["Observational PPO", "Interventional PPO"])]
fig, ax = plt.subplots(figsize=(12, 4.5))
for label in ["Observational PPO", "Interventional PPO"]:
    curve = learned[learned.policy == label].groupby("week").hedge.mean()
    ax.plot(curve.index, curve.values, label=label, color=COLORS[label], linewidth=2)
ax.axvspan(40, 52, color="#71809b", alpha=0.09, label="Q4")
ax.set(title="Deployed mean hedge over held-out weeks", xlabel="Week of year", ylabel="Hedge fraction", ylim=(0, 1))
ax.legend()
fig.tight_layout()
plt.show()
week40 = learned[learned.week == 40].groupby(["year", "policy"]).agg(
    mean_deployed_hedge=("hedge", "mean"),
    probability_below_half=("p_under_half", "mean"),
)
display(week40.round(3))""")
markdown(r"""
## 9 · Real market context: WTI
<a id="9-Real-market-context:-WTI"></a>

These daily published spot prices come from **U.S. EIA via FRED**, not from the SCM. The data helps place the discussion in a real market context. It is **not used for model training, causal-effect estimation, or normalization** in the experiment above.

This is not an intraday feed. Recent observations may be delayed or revised. The provenance record includes the retrieval timestamp, date range and SHA-256 of the CSV. The parser retains negative historical prices and drops missing observations.

The complete loading code is below. By default we use the separate repository snapshot; a missing snapshot or `REFRESH_WTI=True` triggers a public download. A failed download raises an error rather than substituting simulated data.
""")
implementation("data", ["URL", "SOURCE", "parse_csv", "fetch"])
code("""if REFRESH_WTI or not (DATA_DIR / "wti_daily.csv").exists():
    provenance = fetch(DATA_DIR)
else:
    provenance = json.loads((DATA_DIR / "provenance.json").read_text())
raw_csv = (DATA_DIR / "wti_daily.csv").read_bytes()
assert hashlib.sha256(raw_csv).hexdigest() == provenance["sha256"]
wti = pd.read_csv(io.BytesIO(raw_csv), parse_dates=["date"])
display(pd.Series({k: provenance[k] for k in ["provider", "first_observation", "last_observation",
                                             "retrieved_at_utc", "observations", "role"]},
                  name="Data provenance").to_frame())
display(wti.tail().set_index("date"))
fig, ax = plt.subplots(figsize=(13, 4.8))
ax.plot(wti.date, wti.price, color="#138e82", linewidth=1.1)
ax.axhline(0, color="#71809b", linewidth=0.8)
ax.set(title=f"WTI daily spot prices · latest observation {provenance['last_observation']}",
       xlabel="Observation date", ylabel="USD per barrel")
fig.tight_layout()
plt.show()""")
markdown(r"""
## 10 · What this experiment establishes—and what remains open

The simulator demonstrates how a company's historical action can contribute to an observed seasonal pattern, and how explicit interventions produce distinct training worlds. The paired evaluation measures the consequences under one specified regime shift.

The reported policy effect is modest, and depends on the objective, optimization budget, seeds and stress assumptions. The never-hedged policy may win on raw cost while losing on downside utility; always hedging limits exposure at a cost. Those tradeoffs are part of the result.

**It does not establish:**

- that real WTI seasonality was caused by this company's liquidation;
- that the Transformer discovered a 94%-probability seasonal strategy;
- that observational data identified the causal coefficients;
- that an SCM universally improves an RL policy or prevents unseen-shock losses.

Liquidation is tied to season before entry. Separating its real-world effect from exogenous seasonality would require additional assumptions, intervention variation, measurements or an identification strategy. Here that separation is supplied by the simulator designer.

### Sensible next experiments

1. Expand the training-seed count and report paired uncertainty at the seed level.
2. Vary liquidation impact, entry timing and shock size across a predeclared stress grid.
3. Add procurement constraints, actual hedge prices and transaction economics.
4. Estimate a causal model only when intervention records and a defensible identification strategy are available.

### Reproducibility and references

All experiment definitions are visible above. Their source definitions are synchronized with the package by `scripts/build_notebook.py` and checked by repository tests. Rebuilding clears saved outputs; execute the notebook again before publishing it.

- [PPO objective and implementation guidance](https://spinningup.openai.com/en/latest/algorithms/ppo.html)
- [Pearl: A Causal Calculus for Statistical Research](https://proceedings.mlr.press/r0/pearl95a.html)
- [FRED DCOILWTICO](https://fred.stlouisfed.org/series/DCOILWTICO)
- [Repository and reference results](https://github.com/sandipdikshit/Causal-AI)
""")

for i, cell in enumerate(cells):
    cell["id"] = f"causal-ai-{i:02d}"
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12.14"},
    },
}
(ROOT / "Causal_AI_Experiment.ipynb").write_text(json.dumps(notebook, indent=1) + "\n")
print(f"Built notebook with {len(cells)} cells")
